# Generated by Django 2.2.2 on 2019-06-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190606_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('username', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=150)),
                ('is_staff', models.CharField(default='', max_length=150)),
                ('is_active', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
